// <auto-generated />
using System;
using CinemaKioskRecommender.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace CinemaKioskRecommender.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("CinemaKioskRecommender.Domain.Entities.ClientProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstVisitAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GenreMask")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastVisitAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("ClientProfiles");
                });

            modelBuilder.Entity("CinemaKioskRecommender.Domain.Entities.GenreItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres", (string)null);
                });

            modelBuilder.Entity("CinemaKioskRecommender.Domain.Entities.Hall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Halls");
                });

            modelBuilder.Entity("CinemaKioskRecommender.Domain.Entities.KioskSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClientProfileId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("KioskId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientProfileId");

                    b.ToTable("KioskSessions");
                });

            modelBuilder.Entity("CinemaKioskRecommender.Domain.Entities.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("00000000000");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrailerUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("CinemaKioskRecommender.Domain.Entities.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("CinemaKioskRecommender.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HallId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HallId");

                    b.HasIndex("MovieId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("CinemaKioskRecommender.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClientProfileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("KioskSessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientProfileId");

                    b.HasIndex("KioskSessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("CinemaKioskRecommender.Domain.Entities.TicketSeat", b =>
                {
                    b.Property<Guid>("TicketId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("TEXT");

                    b.HasKey("TicketId", "SeatId");

                    b.HasIndex("SeatId");

                    b.ToTable("TicketSeats");
                });

            modelBuilder.Entity("CinemaKioskRecommender.Domain.Entities.ClientProfile", b =>
                {
                    b.OwnsMany("CinemaKioskRecommender.Domain.Entities.ClientPurchase", "Purchases", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("ClientProfileId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("MovieId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("PurchasedAt")
                                .HasColumnType("TEXT");

                            b1.Property<Guid?>("TicketId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("ClientProfileId");

                            b1.ToTable("ClientPurchase");

                            b1.WithOwner()
                                .HasForeignKey("ClientProfileId");
                        });

                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("CinemaKioskRecommender.Domain.Entities.KioskSession", b =>
                {
                    b.HasOne("CinemaKioskRecommender.Domain.Entities.ClientProfile", "ClientProfile")
                        .WithMany("Visits")
                        .HasForeignKey("ClientProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ClientProfile");
                });

            modelBuilder.Entity("CinemaKioskRecommender.Domain.Entities.Seat", b =>
                {
                    b.HasOne("CinemaKioskRecommender.Domain.Entities.Session", "Session")
                        .WithMany("Seats")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("CinemaKioskRecommender.Domain.Entities.Session", b =>
                {
                    b.HasOne("CinemaKioskRecommender.Domain.Entities.Hall", "Hall")
                        .WithMany("Sessions")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CinemaKioskRecommender.Domain.Entities.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaKioskRecommender.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("CinemaKioskRecommender.Domain.Entities.ClientProfile", "ClientProfile")
                        .WithMany("Tickets")
                        .HasForeignKey("ClientProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CinemaKioskRecommender.Domain.Entities.KioskSession", "KioskSession")
                        .WithMany("Tickets")
                        .HasForeignKey("KioskSessionId");

                    b.HasOne("CinemaKioskRecommender.Domain.Entities.Session", "Session")
                        .WithMany("Tickets")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientProfile");

                    b.Navigation("KioskSession");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("CinemaKioskRecommender.Domain.Entities.TicketSeat", b =>
                {
                    b.HasOne("CinemaKioskRecommender.Domain.Entities.Seat", "Seat")
                        .WithMany("TicketSeats")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CinemaKioskRecommender.Domain.Entities.Ticket", "Ticket")
                        .WithMany("TicketSeats")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("CinemaKioskRecommender.Domain.Entities.ClientProfile", b =>
                {
                    b.Navigation("Tickets");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("CinemaKioskRecommender.Domain.Entities.Hall", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("CinemaKioskRecommender.Domain.Entities.KioskSession", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("CinemaKioskRecommender.Domain.Entities.Seat", b =>
                {
                    b.Navigation("TicketSeats");
                });

            modelBuilder.Entity("CinemaKioskRecommender.Domain.Entities.Session", b =>
                {
                    b.Navigation("Seats");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("CinemaKioskRecommender.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("TicketSeats");
                });
#pragma warning restore 612, 618
        }
    }
}
